services:
  portainer:
    extends:
      file: ./portainer/docker-compose.yml
      service: portainer
    networks:
      - monitoring-network

  watchtower:
    extends:
      file: ./watchtower/docker-compose.yml
      service: watchtower
    networks:
      - monitoring-network

  beszel-hub:
    extends:
      file: ./beszel/docker-compose.yml
      service: beszel-hub
    networks:
      - monitoring-network

  beszel-agent:
    extends:
      file: ./beszel/docker-compose.yml
      service: beszel-agent

  kuma:
    extends:
      file: ./kuma/docker-compose.yml
      service: uptime-kuma
    networks:
      - monitoring-network

  caddy:
    extends:
      file: ./caddy/docker-compose.yml
      service: caddy

  prometheus:
    extends:
      file: ./monitoring/docker-compose.yml
      service: prometheus
    networks:
      - monitoring-network

  grafana:
    extends:
      file: ./monitoring/docker-compose.yml
      service: grafana
    networks:
      - monitoring-network

  loki:
    extends:
      file: ./monitoring/docker-compose.yml
      service: loki
    networks:
      - monitoring-network

  promtail:
    extends:
      file: ./monitoring/docker-compose.yml
      service: promtail
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
  caddy-shared-network:
    external: true

volumes:
  beszel_socket:
  caddy:
  caddy_config:
  prometheus_data:
  grafana_data:
  loki_data:
