services:
  portainer:
    extends:
      file: ./portainer/docker-compose.yml
      service: portainer
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  watchtower:
    extends:
      file: ./watchtower/docker-compose.yml
      service: watchtower
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  beszel-hub:
    extends:
      file: ./beszel/docker-compose.yml
      service: beszel-hub
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  beszel-agent:
    extends:
      file: ./beszel/docker-compose.yml
      service: beszel-agent
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  kuma:
    extends:
      file: ./kuma/docker-compose.yml
      service: uptime-kuma
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  caddy:
    extends:
      file: ./caddy/docker-compose.yml
      service: caddy
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  prometheus:
    extends:
      file: ./monitoring/docker-compose.yml
      service: prometheus
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  grafana:
    extends:
      file: ./monitoring/docker-compose.yml
      service: grafana
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  loki:
    extends:
      file: ./monitoring/docker-compose.yml
      service: loki
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  promtail:
    extends:
      file: ./monitoring/docker-compose.yml
      service: promtail
    networks:
      - monitoring-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

networks:
  monitoring-network:
    driver: bridge
  caddy-shared-network:
    external: true

volumes:
  beszel_socket:
  caddy:
  caddy_config:
  prometheus_data:
  grafana_data:
  loki_data:
