version: "3.8"

services:
  caddymanager-mongodb:
    image: mongo:8.0
    container_name: caddymanager-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mBz2SMMt6H7XGCkGZVNCXXADqCPX3dWn
    volumes:
      - caddymanager_db:/data/db
    networks:
      - monitoring-network

  caddymanager-backend:
    image: caddymanager/caddymanager-backend:latest
    container_name: caddymanager-backend
    restart: unless-stopped
    depends_on:
      - caddymanager-mongodb
    env_file:
      - ./backend/.env
    ports:
      - "3011:3011"
    networks:
      - monitoring-network

  caddymanager-frontend:
    image: caddymanager/caddymanager-frontend:latest
    container_name: caddymanager-frontend
    restart: unless-stopped
    depends_on:
      - caddymanager-backend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:80"
    networks:
      - monitoring-network

volumes:
  caddymanager_db:
