auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  chunk_retain_period: 6m
  max_chunk_age: 2h
  chunk_target_size: 1048576
  chunk_encoding: snappy
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 1GB

schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

  index_queries_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 256

limits_config:
  allow_structured_metadata: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_series: 500
  max_query_parallelism: 16
  ingestion_rate_mb: 40
  ingestion_burst_size_mb: 60
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h