server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: "1"

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ["localhost"]
        labels:
          job: caddy
          __path__: /var/log/caddy/*.log

  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 120s
    relabel_configs:
      - source_labels:
          [__meta_docker_container_label_com_docker_compose_service]
        regex: .+
        action: keep
      - source_labels:
          [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_name]
        target_label: container
